name: "Continuous Integration"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm run package
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        verbose:
          - true
          - false
        include-merge-commits:
          - true
          - false
        repo:
          - owner: NixOS
            repo: nixpkgs
            basehead: cc455c004a60e1d65a0fb86ad6cc76168c6bb4d5...67c80531be622641b5b2ccc3a7aff355cb02476b
          - owner: nix-community
            repo: home-manager
            basehead: b0d769691cc379c9ab91d3acec5d14e75c02c02b...59be1f4983ee3689de3172716a6c7e95a6a37bb7
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./
        with:
          owner: ${{ matrix.repo.owner }}
          repo: ${{ matrix.repo.repo }}
          basehead: ${{ matrix.repo.basehead }}
          token: ${{ secrets.GITHUB_TOKEN }}
          verbose: ${{ matrix.verbose }}
          include-merge-commits: ${{ matrix.include-merge-commits }}
  release:
    runs-on: ubuntu-latest
    concurrency: release
    needs:
      - build
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install CI dependencies
        run: npm ci

      - name: Install runtime dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package assets
        run: npm run package

      - name: Release
        env:
          GIT_CREDENTIALS: ${{ secrets.SEMREL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
